### ISSUE TITLE
Too many decimal places!

### ISSUE THREAD

**Issue by ShadAhm** [AmirahParman/MirasTvDistanceCalculator#2]
The site is looking great now but I can see too many decimal places when I enter something:
![image](https://user-images.githubusercontent.com/9742698/232027460-be4c3ca9-49d2-4b32-b6d2-7b5b31d7b3ec.png)

I think it would be great if it were rounded off to maybe 1 or 2 decimal places only.

What do you think?

**Comment by AmirahParman** [comment]
Thanks for your feedback!
I have fixed this issue in commit ff71bbdc7dc320147d5624a2d9fb7c33c1f4592a
