### ISSUE TITLE
Suggestions for refactoring

### ISSUE THREAD

**Issue by ShadAhm** [AmirahParman/MirasTvDistanceCalculator#4]
In calculation.js module, this variable does not need to be exported, since it’s only used within that module:
`export const distanceFormula = 1.2; `

Also, these two functions are perfect for moving out to another “conversion” module:

```
function convertMetersToInches(valueInMetres) {
    return valueInMetres * 39.37;
}

function convertInchToMeter(valueInIches) {
    return valueInIches * 0.0254;
}
```

**Comment by AmirahParman** [comment]
Thank you for your suggestion. I have modularized them!
